/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button } from '@mui/material';
import CheckmarkImage from './assets/images/checkmark_5.png';
import Checkmark1Image from './assets/images/checkmark_4.png';
import Checkmark2Image from './assets/images/checkmark_3.png';
import Checkmark3Image from './assets/images/checkmark_2.png';
import Checkmark4Image from './assets/images/checkmark_1.png';
import Checkmark5Image from './assets/images/checkmark.png';
import { styled } from '@mui/material/styles';

 
const QuestDefault: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.05)`,  
  borderRadius: `6px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `310px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `42px 30px 40px 30px`,  
  boxSizing: `border-box`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Tier1Pro: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(47, 46, 65, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `800`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Price: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `120.34px`,  
  margin: `16px 0px 0px 0px`,  
});
  
const Q49: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `42px`,  
  letterSpacing: `-0.42px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `uppercase`,  
  margin: `0px`,  
});
  
const Month: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(154, 165, 176, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `500`,  
  fontSize: `18px`,  
  letterSpacing: `-0.18px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const ButtonContained: any = styled(Button)({  
  alignSelf: `stretch`,  
  height: `50px`,  
  margin: `18px 0px 0px 0px`,  
});
  
const Features: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `18px 0px 0px 0px`,  
});
  
const IncludedFeatures: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `800`,  
  fontSize: `14px`,  
  letterSpacing: `0.84px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const FeatureRow: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const UnlimitedComponentSy: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const FeatureRow1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark1: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const NestedComponents: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const FeatureRow2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark2: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const BuildFullAppsOrAddTo: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const FeatureRow3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark3: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const GeneratesReactJsCode: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const FeatureRow4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark4: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const DesignSystemSupportB: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const FeatureRow5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `14px 0px 0px 0px`,  
});
  
const Checkmark5: any = styled("img")({  
  height: `12px`,  
  width: `15px`,  
  margin: `0px`,  
});
  
const CleanCodeWithSeparat: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0.36px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Chip: any = styled("div")({  
  backgroundColor: `rgba(46, 125, 50, 1)`,  
  borderRadius: `50px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px 6px`,  
  boxSizing: `border-box`,  
  height: `28px`,  
  width: `127px`,  
  left: `91px`,  
  top: `-14px`,  
});
  
const Frame1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px 5px`,  
  boxSizing: `border-box`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `3px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const MostPopular: any = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `0.5px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
});
 
function Pricing7(): JSX.Element {
  return (
    <QuestDefault >
       <Top >
         <Tier1Pro >
           {`TIER 1 - PRO`}
             </Tier1Pro>
         <Price >
           <Q49 >
             {`$49`}
               </Q49>
           <Month >
             {`/month`}
               </Month>
         </Price>
       </Top>
       <ButtonContained variant="contained" size="large" color="success"    > Sign-up TODAY </ButtonContained>
       <Features >
         <IncludedFeatures >
           {`Included Features:`}
             </IncludedFeatures>
         <FeatureRow >
           <Checkmark  src={CheckmarkImage} alt={"checkmark"}/>
           <UnlimitedComponentSy >
             {`Unlimited Component Syncs`}
               </UnlimitedComponentSy>
         </FeatureRow>
         <FeatureRow1 >
           <Checkmark1  src={Checkmark1Image} alt={"checkmark"}/>
           <NestedComponents >
             {`Nested Components`}
               </NestedComponents>
         </FeatureRow1>
         <FeatureRow2 >
           <Checkmark2  src={Checkmark2Image} alt={"checkmark"}/>
           <BuildFullAppsOrAddTo >
             {`Build Full Apps or add to your exiting`}
               </BuildFullAppsOrAddTo>
         </FeatureRow2>
         <FeatureRow3 >
           <Checkmark3  src={Checkmark3Image} alt={"checkmark"}/>
           <GeneratesReactJsCode >
             {`Generates react.js code`}
               </GeneratesReactJsCode>
         </FeatureRow3>
         <FeatureRow4 >
           <Checkmark4  src={Checkmark4Image} alt={"checkmark"}/>
           <DesignSystemSupportB >
             {`Design system support built-in`}
               </DesignSystemSupportB>
         </FeatureRow4>
         <FeatureRow5 >
           <Checkmark5  src={Checkmark5Image} alt={"checkmark"}/>
           <CleanCodeWithSeparat >
             {`Clean code with separation of concerns`}
               </CleanCodeWithSeparat>
         </FeatureRow5>
       </Features>
       <Chip >
         <Frame1 >
           <Text >
             <MostPopular >
               {`Most Popular`}
                 </MostPopular>
           </Text>
         </Frame1>
       </Chip>
     </QuestDefault>
   );
}

export default Pricing7;
