/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Ig21Image from './assets/images/IG2_1.png';
import Ig22Image from './assets/images/IG2_2.png';
import { styled } from '@mui/material/styles';

 
const Property1Default = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `210px`,  
  height: `226px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `27px 19px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Frame1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  left: `92px`,  
  top: `-16px`,  
});
  
const Ig21 = styled("img")({  
  height: `172px`,  
  width: `172px`,  
  margin: `0px`,  
});
  
const Ig22 = styled("img")({  
  height: `86px`,  
  width: `86px`,  
  margin: `0px`,  
});
 
function Q7AbsoluteGroupOk() {
  return (
    <Property1Default >
       <Frame1 >
         <Ig21  src={Ig21Image} alt={"IG2 1"}/>
         <Ig22  src={Ig22Image} alt={"IG2 2"}/>
       </Frame1>
     </Property1Default>
   );
}

export default Q7AbsoluteGroupOk;
