/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Avatar1Image from './assets/images/Avatar_1.png';
import { styled } from '@mui/material/styles';
import RatingStar from './RatingStar';

 
const Property1Default: any = styled("div")(({ theme }: any) =>({  
  backgroundColor: theme.palette["Background"]["Paper"],  
  boxShadow: theme.customShadows["Elevation"]["Outlined Light"].boxShadow,  
  borderRadius: `4px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `249.99px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `30px`,  
  boxSizing: `border-box`,  
}));
  
const Row: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Avatar1: any = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  margin: `0px`,  
});
  
const Name: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Top: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const EllenCho: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `14px`,  
  textTransform: `none`,  
  width: `60px`,  
  height: `11px`,  
  margin: `0px`,  
}));
  
const Row1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Rating: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const RatingStar1: any = styled(RatingStar)(({ theme }: any) =>({  
  width: `14px`,  
  height: `13.17px`,  
  margin: `0px`,  
}));
  
const RatingStar2: any = styled(RatingStar)(({ theme }: any) =>({  
  width: `14px`,  
  height: `13.17px`,  
  margin: `0px 0px 0px 2px`,  
}));
  
const RatingStar3: any = styled(RatingStar)(({ theme }: any) =>({  
  width: `14px`,  
  height: `13.17px`,  
  margin: `0px 0px 0px 2px`,  
}));
  
const RatingStar4: any = styled(RatingStar)(({ theme }: any) =>({  
  width: `14px`,  
  height: `13.17px`,  
  margin: `0px 0px 0px 2px`,  
}));
  
const RatingStar5: any = styled(RatingStar)(({ theme }: any) =>({  
  width: `14px`,  
  height: `13.17px`,  
  margin: `0px 0px 0px 2px`,  
}));
  
const UxDesigner: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Disabled"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `14px`,  
  textTransform: `none`,  
  height: `11px`,  
  width: `60px`,  
  margin: `2px 0px 0px 0px`,  
}));
  
const Row2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Top1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const LoremIpsumDolorSitAm: any = styled("div")(({ theme }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Secondary"],  
  fontStyle: `normal`,  
  fontFamily: `Heebo`,  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `18px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
 
function Rating5(): JSX.Element {
  return (
    <Property1Default >
       <Row >
         <Avatar1  src={Avatar1Image} alt={"Avatar"}/>
         <Name >
           <Top >
             <EllenCho >
               {`Ellen Cho`}
                 </EllenCho>
             <Row1 >
               <Rating >
                 <RatingStar1   />
                 <RatingStar2   />
                 <RatingStar3   />
                 <RatingStar4   />
                 <RatingStar5   />
               </Rating>
             </Row1>
           </Top>
           <UxDesigner >
             {`UX Designer`}
               </UxDesigner>
         </Name>
       </Row>
       <Row2 >
         <Top1 >
           <LoremIpsumDolorSitAm >
             {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quam leo urna turpis semper sed a vulputate mi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. `}
               </LoremIpsumDolorSitAm>
         </Top1>
       </Row2>
     </Property1Default>
   );
}

export default Rating5;
