/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Frame15044 from './Frame15044';

 
const Stacking1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Q001: any = styled(Frame15044)(({ theme }: any) =>({  
  margin: `0px`,  
}));
  
const Q002: any = styled(Frame15044)(({ theme }: any) =>({  
  margin: `0px 0px 0px -16px`,  
}));
  
const Q003: any = styled(Frame15044)(({ theme }: any) =>({  
  margin: `0px 0px 0px -16px`,  
}));
  
const Q4: any = styled(Frame15044)(({ theme }: any) =>({  
  margin: `0px 0px 0px -16px`,  
}));
 
function Stacking(): JSX.Element {
  return (
    <Stacking1 >
       <Q001   />
       <Q002   />
       <Q003   />
       <Q4   />
     </Stacking1>
   );
}

export default Stacking;
