/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useVariantTest = () => {
  let data: any = {};
  const somethingHere = (
    param1:any,  param2: any,  param3: any
  ): any => {
  //comment here
  };

  const clickingClicking = (param1:any): any => {};
  const onHover = (): any => {};
  let fns: any = {somethingHere, clickingClicking, onHover};
  return {data, fns};
}

export default useVariantTest;
