/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

const useCard2 = () => {
  const handleButtonClickedThiagoTestFinal = (): any => {};
  const handleButtonClickedThiagoTest5 = (): any => {};
  const handleButtonClickedThiagoTest4 = (): any => {};
  const handleButtonClickedThiagoTest3 = (): any => {};
  const handleButtonClickedThiagoTest2 = (): any => {};
  let data: any = {};
  const handleButtonClickedThiagoTest = (): any => {};

  let fns: any = { handleButtonClickedThiagoTest ,handleButtonClickedThiagoTest2,handleButtonClickedThiagoTest3,handleButtonClickedThiagoTest4,handleButtonClickedThiagoTest5,handleButtonClickedThiagoTestFinal};
  return { data, fns };
};

export default useCard2;
